services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo-compose:27017/feedback-app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - '8080:80'

  mongo:
    image: mongo:latest
    container_name: mongo-compose
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: feedbackdb

volumes:
  mongo-data: